using System.Security.Cryptography;
using System.Text.Json;
using EVoteUG.Infrastructure.Security;
using EVoteUG.Shared.Enums;
using EVoteUG.Shared.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace EVoteUG.Infrastructure.Data;

public static class DbInitializer
{
    public static async Task SeedAsync(EVoteUGDbContext context, IConfiguration? configuration = null, ILogger? logger = null)
    {
        // 1. Ensure SuperAdmin exists without hardcoding credentials in code
        if (!await context.Admins.AnyAsync())
        {
            var adminUsername = configuration?["InitialAdmin:Username"] 
                                ?? Environment.GetEnvironmentVariable("INITIAL_ADMIN_USERNAME") 
                                ?? "ec_admin";

            var adminEmail = configuration?["InitialAdmin:Email"] 
                             ?? Environment.GetEnvironmentVariable("INITIAL_ADMIN_EMAIL") 
                             ?? "ec@ug.edu.gh";

            var initialAdminPassword = configuration?["InitialAdmin:Password"]
                                       ?? Environment.GetEnvironmentVariable("INITIAL_ADMIN_PASSWORD");

            var isAutoGenerated = false;
            if (string.IsNullOrWhiteSpace(initialAdminPassword))
            {
                initialAdminPassword = GenerateSecureRandomPassword(16);
                isAutoGenerated = true;
            }

            var defaultAdmin = new Admin
            {
                Username = adminUsername,
                FullName = "Electoral Commission Administrator",
                Email = adminEmail,
                PasswordHash = PasswordHasher.HashPassword(initialAdminPassword),
                Role = UserRole.SuperAdmin,
                MustChangePassword = true,
                IsActive = true,
                CreatedAt = DateTime.UtcNow
            };
            context.Admins.Add(defaultAdmin);
            await context.SaveChangesAsync();

            if (isAutoGenerated)
            {
                var banner = $"""

                ================================================================================
                [SECURITY NOTICE] INITIAL SUPERADMIN ACCOUNT CREATED
                Username: {defaultAdmin.Username}
                Temporary Password: {initialAdminPassword}
                IMPORTANT: Copy this password. You will be required to change it on first login.
                ================================================================================
                """;
                Console.WriteLine(banner);
                logger?.LogWarning("Initial SuperAdmin created with temporary password. Please check console output and change password upon login.");
            }
        }

        // 2. Optional: Load seed data from external seed_data.json file if present
        var seedFilePath = Path.Combine(AppContext.BaseDirectory, "seed_data.json");
        if (File.Exists(seedFilePath) && !await context.Elections.AnyAsync())
        {
            try
            {
                var jsonContent = await File.ReadAllTextAsync(seedFilePath);
                var seedData = JsonSerializer.Deserialize<SeedDataModel>(jsonContent, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                });

                if (seedData?.Students != null && seedData.Students.Count > 0 && !await context.Students.AnyAsync())
                {
                    foreach (var s in seedData.Students)
                    {
                        var pwd = string.IsNullOrWhiteSpace(s.PasswordHash) ? GenerateSecureRandomPassword(12) : s.PasswordHash;
                        s.PasswordHash = PasswordHasher.HashPassword(pwd);
                    }
                    context.Students.AddRange(seedData.Students);
                }

                if (seedData?.Elections != null && seedData.Elections.Count > 0)
                {
                    context.Elections.AddRange(seedData.Elections);
                }

                await context.SaveChangesAsync();
                logger?.LogInformation("Loaded seed data from external seed_data.json.");
            }
            catch (Exception ex)
            {
                logger?.LogError(ex, "Failed to load external seed_data.json.");
            }
        }
    }

    private static string GenerateSecureRandomPassword(int length = 16)
    {
        const string validChars = "ABCDEFGHJKLMNOPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz0123456789!@#$%^&*";
        var result = new char[length];
        var randomBytes = new byte[length];
        using (var rng = RandomNumberGenerator.Create())
        {
            rng.GetBytes(randomBytes);
        }

        for (int i = 0; i < length; i++)
        {
            result[i] = validChars[randomBytes[i] % validChars.Length];
        }

        return new string(result);
    }

    private class SeedDataModel
    {
        public List<Student>? Students { get; set; }
        public List<Election>? Elections { get; set; }
    }
}
